[env]
MISE_ENV_FILE = ".env"

[tools]
dprint = "0.47.2"
watchexec = "2.1.2"
go = "1.23.1"
mkcert = "1.4.4"
"go:honnef.co/go/tools/cmd/staticcheck" = "0.6.0-0.dev"

[tasks."setup"]
description = "Setup the project"
run = [
  # Install dependencies
  "go mod download",
  "go mod tidy",
  "mise reshim",
  # Create certificates for localhost
  "mkcert -install",
  "mkdir -p .ssh && mkcert -cert-file=.ssh/cert.pem -key-file=.ssh/cert-key.pem localhost 127.0.0.1 ::1 ${DOMAIN_NAME}",
]
sources = ["go.mod", ".mise.toml", "*/**/*.go"]
outputs = ["go.sum"]

[tasks."default"]
hide = true
depends = ["dev"]

[tasks."dev"]
description = "Run the server and watch for changes"
run = "mise watch -t serve -r"

[tasks."serve"]
description = "Run the server"
run = "go run ./cmd/server"
sources = ["go.mod", "*/**/*.go"]
# Waiting for: https://github.com/jdx/mise/issues/2526
# depends = ["setup"]

[tasks."format"]
description = "Format files in the project"
run = "dprint fmt"

[tasks."check:format"]
description = "Check formatting"
run = "dprint check"

[tasks."check:lint"]
description = "Check linting"
run = "staticcheck ./..."

[tasks."test:unit"]
description = "Run unit tests"
run = "go test ./..."

[settings]
activate_aggressive = true
asdf_compat = true
experimental = true
yes = true
