# [[env]]
# _.file = ".env"

[tools]
go = "1.23.1"
dprint = "0.47.2"
watchexec = "2.1.2"

[tasks."setup"]
description = "Setup the project"
run = [
  "go mod download",
  "go mod tidy",
]
sources = ["go.mod", ".mise.toml", "*/**/*.go"]
outputs = ["go.sum"]

[tasks."default"]
hide = true
depends = ["dev"]

[tasks."dev"]
description = "Run the server and watch for changes"
run = "mise watch -t serve -r"

[tasks."serve"]
description = "Run the server"
run = "go run ./cmd/server"
sources = ["go.mod", "*/**/*.go"]
# Waiting for: https://github.com/jdx/mise/issues/2526
# depends = ["setup"]

[tasks."format"]
description = "Format files in the project"
run = "dprint fmt"

[tasks."test:unit"]
description = "Run unit tests"
run = "go test ./..."

[tasks."check:format"]
description = "Check formatting"
run = "dprint check"

[tasks."check:vet"]
description = "Run go vet"
run = "go vet ./..."

[settings]
experimental = true
asdf_compat = true
yes = true
